### ISSUE TITLE
SoftRoCE failing while installation of user space libraries

### ISSUE THREAD

**Issue by LakshayNagpal** [SoftRoCE/librxe-dev#11]
I am following this link: https://community.mellanox.com/docs/DOC-2184
and I am stuck at the point where we need to build user space libraries at point number 2. in user space libraries installation from the above link.

And I'm getting the following error:

```
CMake Error at providers/bnxt_re/cmake_install.cmake:62 (FILE):
  file INSTALL cannot find
  "/usr/src/rdma-core/build/lib/libbnxt_re-rdmav2.so".
Call Stack (most recent call first):
  cmake_install.cmake:47 (INCLUDE)
 
make: *** [install] Error 1
```

Please help me out as I'm stuck at this position for the past 1.5 month and couldn't find a solution from any developer or internet.

**Comment by LakshayNagpal** [comment]
is it possible to bypass this error by setting some flags?

Also, how should I start with the codebase so that I can understand it well?

**Comment by matthelb** [comment]
If you are following the directions from https://web.archive.org/web/20180531203341/https://community.mellanox.com/docs/DOC-2184, note that the `build.sh` script builds libraries in-place and is not intended to be used in conjunction with the installation scripts that get generated in the build subdirectory (`build/Makefile` --> `cd build; sudo make install`).

It appears that the `libbnxt_re-rdmav` file gets renamed or deleted during the `make install` script, despite being needed later in the same script.

To fix this problem, I used the build script to build all the necessary libraries and then installed the files manually:

    bash build.sh
    sudo mkdir /usr/local/lib/rdma-core
    sudo cp -r build/lib/* /usr/local/lib/rdma-core
    sudo cp -r build/bin/* /usr/local/bin

**Comment by LakshayNagpal** [comment]
Hi @mburke13

Thanks for the solution but unfortunately due to helplessness and lack of resources, I dropped this project long time back.

Thanks once again :)
