### ISSUE TITLE
modprobe: FATAL: Module rdma_rxe not found  ;rxe modules not loaded

### ISSUE THREAD

**Issue by Peng-git-hub** [SoftRoCE/librxe-dev#9]
When i load rdma_rxe kernel module using the command of sudo rxe_cfg start, it was failed saying
modprobe: FATAL: Module rdma_rxe not found.
rxe modules not loaded

And no file or directory matches the "/sys/module/rdma_rxe/parameters".
This problem has been bothering me for a long time，looking for your help.

**Comment by monis410** [comment]
try modinfo rdma_rxe or modinfo ib_rxe
Do you see the modules?

**Comment by Peng-git-hub** [comment]
when i try modinfo rdma_rxe，it shows
modinfo: ERROR: Module rdma_rxe not found.

when i try modinfo ib_rxe，it shows
filename:       /lib/modules/4.0.0+/kernel/drivers/infiniband/hw/rxe/ib_rxe.ko
version:        0.1
license:        Dual BSD/GPL
description:    Soft RDMA transport
author:         Bob Pearson, Frank Zago, John Groves, Kamal Heib
srcversion:     771D3CC80778DF403A24401
depends:        ip6_udp_tunnel,ib_core,udp_tunnel
intree:         Y
vermagic:       4.0.0+ SMP mod_unload modversions
signer:         Magrathea: Glacier signing key
sig_key:        36:18:A9:1B:AE:B8:9B:F9:9A:5E:52:42:80:F1:08:5E:79:33:FF:25
sig_hashalgo:   sha512

**Comment by Peng-git-hub** [comment]
when i try modinfo rdma_rxe，it shows
modinfo: ERROR: Module rdma_rxe not found.

when i try modinfo ib_rxe，it shows
filename: /lib/modules/4.0.0+/kernel/drivers/infiniband/hw/rxe/ib_rxe.ko
version: 0.1
license: Dual BSD/GPL
description: Soft RDMA transport
author: Bob Pearson, Frank Zago, John Groves, Kamal Heib
srcversion: 771D3CC80778DF403A24401
depends: ip6_udp_tunnel,ib_core,udp_tunnel
intree: Y
vermagic: 4.0.0+ SMP mod_unload modversions
signer: Magrathea: Glacier signing key
sig_key: 36:18:A9:1B:AE:B8:9B:F9:9A:5E:52:42:80:F1:08:5E:79:33:FF:25
sig_hashalgo: sha512

**Comment by monis410** [comment]
You probably have an older kernel
Are you on upstream kernel?

**Comment by Peng-git-hub** [comment]
root@qipeng-OptiPlex-380:/home/qipeng/softroce/librxe-dev# uname -a
Linux qipeng-OptiPlex-380 4.0.0+ #1 SMP Mon Nov 14 12:45:01 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
when i try "uname -a",it's the new kernel.
But when i try “sudo dpkg --get-selections |grep linux”, there is no no kernel of 4.0.0+：
qipeng@qipeng-OptiPlex-380:~$ sudo dpkg --get-selections |grep linux
[sudo] password for qipeng: 
libselinux1:amd64               install
linux-firmware                  install
linux-generic-lts-vivid             install
linux-headers-3.19.0-25             install
linux-headers-3.19.0-25-generic         install
linux-headers-generic-lts-vivid         install
linux-image-3.19.0-25-generic           install
linux-image-extra-3.19.0-25-generic     install
linux-image-generic-lts-vivid           install
linux-libc-dev:amd64                install
linux-libc-dev-arm64-cross          install
linux-sound-base                install
pptp-linux                  install
syslinux                    install
syslinux-common                 install
syslinux-legacy                 install
util-linux                  install
SO,I'm puzzled about this situation.

**Comment by monis410** [comment]
How is this relevant to Soft RoCE

**Comment by manishrajmohanty** [comment]
I'm having the same problem : rdma_rxe module not loaded

manish@manish-Inspiron-N5110:~$ sudo rxe_cfg start
modprobe: FATAL: Module rdma_rxe not found in directory /lib/modules/4.17.0-rc3
rdma_rxe module not loaded
  Name    Link  Driver   Speed  NMTU  IPv4_addr    RDEV  RMTU  
  wlp9s0  yes   iwlwifi         1500  192.168.0.9 

Can you help me?

**Comment by Luo-Liang** [comment]
@manishrajmohanty looks like your kernel is not built with SoftRoce support :(
